In [1]:
import numpy as np
import NLA # import numerical linear algebra module you wrote (see NLA.py)

## Solve lower-triangular linear system (Forward Substitution)

In [2]:
# Generate data
n = 10
L = np.zeros((n,n))
for i in range(n):
    L[i,i] = 1
    for j in range(i):
        L[i,j] = np.random.randint(-50,50)
x = np.random.randint(-50,50,n)
b = L.dot(x)
print('L: \n{}'.format(L))
print('x: \n{}'.format(x))
print('b: \n{}'.format(b))

L: 
[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [-43.   1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 43.  38.   1.   0.   0.   0.   0.   0.   0.   0.]
 [-30. -16.   3.   1.   0.   0.   0.   0.   0.   0.]
 [  0. -22.  -5.  -1.   1.   0.   0.   0.   0.   0.]
 [ 11. -21. -11.   4.  47.   1.   0.   0.   0.   0.]
 [ 45.   3.  18.  16. -22.   8.   1.   0.   0.   0.]
 [-19. -14.  -3. -10. -26.   5.  12.   1.   0.   0.]
 [-27.   9.  11. -40.  24.  24. -14.  -6.   1.   0.]
 [-49. -49. -32.   4. -25.   0. -41. -35. -19.   1.]]
x: 
[-21  45 -28   9 -17  42   8 -49  27  22]
b: 
[  -21.   948.   779.  -165.  -876. -1589.  -452.   462.  1113.  1077.]


In [3]:
y = NLA.forward_sub(L,b)
print('Computed solution: \n{}'.format(y))
print('Computed true solution?: \n{}'.format(np.allclose(x,y,atol=1e-6)))

Computed solution: 
[-21.  45. -28.   9. -17.  42.   8. -49.  27.  22.]
Computed true solution?: 
True


## Solve upper-triangular linear system (Backward Substitution)

In [4]:
# Generate data
n = 10
U = np.zeros((n,n))
for i in range(n):
    for j in range(i,n):
        U[i,j] = np.random.randint(-50,50)
x = np.random.randint(-50,50,n)
b = U.dot(x)
print('U: \n{}'.format(U))
print('x: \n{}'.format(x))
print('b: \n{}'.format(b))

U: 
[[ 48.  42. -37.  44.   1.   9.  -9. -18.  32.  11.]
 [  0. -41.  -6.  11.  41. -29. -14. -48.  40.  19.]
 [  0.   0.   5. -47.  49.  40.  29. -13. -49.  -3.]
 [  0.   0.   0. -29.   7.   9.  44.  39.  19.  32.]
 [  0.   0.   0.   0. -20. -33.  -5. -19. -50.   9.]
 [  0.   0.   0.   0.   0.   2.  -3. -19.  28.  44.]
 [  0.   0.   0.   0.   0.   0.  19.  36. -42. -15.]
 [  0.   0.   0.   0.   0.   0.   0.  32. -16. -31.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -32. -30.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  45.]]
x: 
[  0  -4 -28 -16  40  37 -11 -18 -38  40]
b: 
[  184.   981.  5709.   449.   636.  1145.   139. -1208.    16.  1800.]


In [5]:
y = NLA.backward_sub(U,b)
print('Computed solution: \n{}'.format(y))
print('Computed true solution?: \n{}'.format(np.allclose(x,y,atol=1e-6)))

Computed solution: 
[  0.  -4. -28. -16.  40.  37. -11. -18. -38.  40.]
Computed true solution?: 
True


## Solve general linear system

In [6]:
# Generate data
n = 10
A = np.random.randint(-50,50,(n,n)).astype('float')
x = np.random.randint(-50,50,n).astype('float')
b = A.dot(x)
print('A: \n{}'.format(A))
print('x: \n{}'.format(x))
print('b: \n{}'.format(b))

A: 
[[ 36. -50. -30.   9.  30.  25.  25.  30.  27.  -1.]
 [ 38.  36.  45. -39.  -7.  -7.  18. -24. -14.   3.]
 [-19. -30.   7. -44.  -8. -40.  13.  -7. -44.  24.]
 [-30. -40.  45. -28.  46. -24.  26. -32.  -3.  16.]
 [ -2. -22. -31. -31.  37. -15. -29. -14.  23.  16.]
 [-34. -31.   7.  18.  43. -23.  -8.   2. -28. -14.]
 [-47. -15.  48.   2.  23.   2. -15.  49.  44.  11.]
 [ 45. -13. -34.  30.  47.   6. -15. -16.  35.  42.]
 [ 25. -42.  45.  25.   4.  46.   5. -22.  12.  25.]
 [-12.  43. -35.  -7. -38.  34.  21.   2. -34.   6.]]
x: 
[ 34. -14.   1.  14.  14.   2. -44.  36.   4.  37.]
b: 
[ 2541. -1426. -1139. -1927.  1719.  -113.  2021.  4546.  1942. -2373.]


In [7]:
y = NLA.solve(A,b)
print('Computed solution: \n{}'.format(y))
print('Computed true solution?: \n{}'.format(np.allclose(x,y,atol=1e-6)))

Computed solution: 
[ 34. -14.   1.  14.  14.   2. -44.  36.   4.  37.]
Computed true solution?: 
True


## QR

In [8]:
# Generate data
n,m = 6,4
A = np.random.randint(-50,50, (n,m)).astype('float')
print('Data: \n{}'.format(A))

Data: 
[[-38. -49.  26. -31.]
 [-34.  47. -25.  16.]
 [-47. -37.  13.  21.]
 [  9. -50. -50. -38.]
 [ 46. -23. -45. -11.]
 [-41. -24.  20.  -6.]]


### Reduced QR factorization

In [9]:
Q,R = NLA.QR(A, reduced=True)
print('Q factor: \n{}'.format(Q))
print('R factor: \n{}'.format(R))
check_cols = np.allclose(Q.T.dot(Q), np.eye(m))
print('Columns of Q orthogonal?: \n{}'.format(check_cols))

Q factor: 
[[-0.40770749 -0.44025765  0.17877063 -0.49578551]
 [-0.36479091  0.5464478  -0.68833756 -0.11841961]
 [-0.50426979 -0.30017659 -0.09909007  0.77004277]
 [ 0.0965623  -0.53344244 -0.62169193 -0.2681182 ]
 [ 0.49354064 -0.31915793 -0.31114869  0.25747968]
 [-0.43989492 -0.17618004  0.03315511 -0.09499738]]
R factor: 
[[ 93.20407716  15.86840453 -43.87147134 -10.24633288]
 [  0.          96.60328016   8.50043863  40.92607361]
 [  0.           0.          66.31769406   8.21181634]
 [  0.           0.           0.          37.5717345 ]]
Columns of Q orthogonal?: 
True


### Full QR factorization

In [10]:
Q,R = NLA.QR(A, reduced=False)
print('Q factor: \n{}'.format(Q))
print('R factor: \n{}'.format(R))
check_cols = np.allclose(Q.T.dot(Q), np.eye(n))
print('Columns of Q orthogonal?: \n{}'.format(check_cols))

Q factor: 
[[-0.40770749 -0.44025765  0.17877063 -0.49578551  0.41701352  0.43391857]
 [-0.36479091  0.5464478  -0.68833756 -0.11841961  0.26246147  0.10772451]
 [-0.50426979 -0.30017659 -0.09909007  0.77004277 -0.07719698  0.21647614]
 [ 0.0965623  -0.53344244 -0.62169193 -0.2681182  -0.49719457 -0.02289587]
 [ 0.49354064 -0.31915793 -0.31114869  0.25747968  0.69327821 -0.10398022]
 [-0.43989492 -0.17618004  0.03315511 -0.09499738  0.15302684 -0.86134318]]
R factor: 
[[ 93.20407716  15.86840453 -43.87147134 -10.24633288]
 [  0.          96.60328016   8.50043863  40.92607361]
 [  0.           0.          66.31769406   8.21181634]
 [  0.           0.           0.          37.5717345 ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
Columns of Q orthogonal?: 
True
